name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    permissions:
      # If you want to clone the repository as part of your setup steps,
      # for example to install dependencies, you'll need the `contents: read` permission.
      contents: read

    # Any steps you define will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v5
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.OS }}-${{ env.pythonLocation }}-${{ hashFiles('requirements/REQUIREMENTS-CI.txt') }}

      - name: Install Dependencies
        run: |
          make install-dev

      - name: flake8 linting and mypy static type checker
        run: |
          make lint mypy
